import { test,expect } from '@playwright/test';
test.skip(!process.env.GENERATION_BROWSER_TEST,'Synthetic generation fixture required');
test('passage practice survives reload, keeps failures as alerts and protects publication',async({page})=>{
 await page.goto('/practice');await expect(page.getByRole('heading',{name:'Use what you’ve studied.'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Export prompt',exact:true})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Download prompt'})).toHaveCount(0);
 await expect(page.getByLabel('Practice type')).toHaveCount(0);
 const headers={Origin:new URL(page.url()).origin};
 const exported=await page.request.post('/api/generation',{headers,data:{action:'export',purpose:'passage',topic:'Synthetic reading'}});expect(exported.ok()).toBe(true);const id=(await exported.json()).id;
 const snapshot=await (await page.request.get(`/api/generation?run=${id}`)).json();const itemId=snapshot.scope.targets[0].id;
 const draft={version:1,kind:'passage',title:'Synthetic meal',japanese:'食べる。',translation:'Eat.',uses:[{itemId,start:0,end:3,reading:'たべる',sense:'eat'}],support:[],issues:[],omissions:[],sentences:[{start:0,end:4,translation:'Eat.'}],questions:[0,1].map(i=>({prompt:`What happens? ${i+1}`,targetIds:[itemId],options:[{label:'A',text:'Eating'},{label:'B',text:'Sleeping'}],answer:'A',explanation:'Eating is in the passage.',evidence:{start:0,end:3}}))};
 const imported=await page.request.post('/api/generation',{headers,data:{action:'import',runId:id,draft,modelId:'synthetic'}});expect(imported.ok()).toBe(true);await page.reload();
 await page.getByRole('button',{name:/Synthetic reading/}).click();await expect(page.getByRole('heading',{name:'Synthetic meal'})).toBeVisible();
 expect((await (await page.request.get(`/api/generation?run=${id}`)).json()).report.analyzerStatus).toBe('ready');
 const word=page.getByRole('button',{name:'Word help: 食べる',exact:true}),ruby=word.locator('rt');
 await expect(ruby).toHaveCSS('visibility','hidden');
 await word.hover();
 await expect(ruby).toHaveCSS('visibility','visible');
 await expect(word).toHaveCSS('background-color','rgba(0, 0, 0, 0)');
 await expect(word).toHaveCSS('border-bottom-style','solid');
 await expect(page.getByRole('complementary',{name:'Contextual word help'})).toHaveCount(0);
 await page.mouse.move(0,0);await expect(ruby).toHaveCSS('visibility','hidden');
 await word.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await expect(word).toBeFocused();await expect(ruby).toHaveCSS('visibility','visible');
 await word.click();await expect(page.getByRole('complementary',{name:'Contextual word help'})).toBeVisible();
 await page.getByRole('button',{name:'Close word help'}).click();
 await page.getByRole('combobox',{name:/^Furigana/}).selectOption('off');
 await expect(word.locator('rt')).toHaveCount(0);
 await page.getByRole('combobox',{name:/^Furigana/}).selectOption('request');
 await page.locator('.publication-review > summary').click();
 await expect(page.getByRole('button',{name:'Approve for reuse'})).toBeDisabled();
 await page.screenshot({path:'.local/practice-polished-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.locator('.publication-review').scrollIntoViewIfNeeded();
 await page.screenshot({path:'.local/practice-polished-mobile.png',fullPage:true});
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:'Sentence help · 1',exact:true}).click();
 await expect(page.getByText('Eat.',{exact:false}).first()).toBeVisible();
 await page.getByLabel('Word or grammar help').selectOption('0');
 await expect(page.getByRole('complementary',{name:'Contextual word help'})).toBeFocused();
 await page.keyboard.press('Escape');
 await expect(page.getByLabel('Word or grammar help')).toBeFocused();
 await page.getByLabel('Reviewer',{exact:true}).fill('Synthetic browser reviewer');
 await page.getByLabel('I checked Japanese, contextual readings, senses and translation.').check();
 await page.getByLabel('I accept untracked support for this content without marking it familiar.').check();
 await page.getByLabel('I checked both answers, distractors and passage evidence.').check();
 const resolutions=page.getByLabel(/Checked resolution for/);
 for(let n=0;n<await resolutions.count();n++)await resolutions.nth(n).fill('Synthetic fixture reviewed for this test.');
 await page.getByRole('button',{name:'Approve for reuse',exact:true}).click();
 await expect(page.getByText('Generated · human reviewed',{exact:true}).first()).toBeVisible();
 await page.getByRole('combobox',{name:/^Furigana/}).selectOption('all');
 await expect(page.locator('ruby rt')).toHaveText('たべる');
 await page.getByLabel('Word or grammar help').selectOption('0');
 await page.getByRole('button',{name:'Save word with context'}).click();
 await expect(page.getByRole('complementary',{name:'Contextual word help'}).getByRole('status')).toContainText('Context saved.');
 await page.getByRole('button',{name:'Close word help'}).click();
 await page.locator('summary').filter({hasText:'Report a problem'}).click();
 await page.getByLabel('Report a problem').fill('Synthetic retirement check');
 await page.getByRole('button',{name:'Report and retire'}).click();
 await expect(page.getByText('Generated · retired',{exact:true})).toBeVisible();
 const blocked=await page.request.post('/api/generation',{headers:{Origin:'http://evil.example'},data:{action:'hide',runId:id}});expect(blocked.status()).toBe(403);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(page.getByRole('button',{name:'Hide this item',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Hide this item',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Synthetic meal'})).not.toBeVisible();
 const next=await page.request.post('/api/generation',{headers,data:{action:'export',purpose:'passage',topic:'Next reading'}});expect(next.ok()).toBe(true);
 await page.request.post('/api/generation',{headers,data:{action:'import',runId:(await next.json()).id,draft,modelId:'synthetic'}});await page.reload();
 await page.route('**/api/generation?run=*',route=>route.fulfill({json:{id,status:'failed',provider:'gemini',modelId:'synthetic',scope:{targets:[],support:[]},prompt:'Synthetic failure',report:{failure:'network'}}}));
 await page.locator('.practice-history button').first().click();
 await expect(page.getByRole('region',{name:'Contextual practice'}).getByRole('alert')).toContainText('Generation timed out or could not connect');
 await expect(page.getByRole('button',{name:'Approve for reuse'})).toHaveCount(0);
 await expect(page.getByText('Generation did not finish')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Dictionary / selected text'})).toHaveCount(0);
 await page.getByRole('button',{name:'Dismiss'}).click();await expect(page.getByRole('region',{name:'Contextual practice'}).getByRole('alert')).toHaveCount(0);
});
test('large reviewed passages cross the former request limit without bypassing dispositions',async({page})=>{
 await page.goto('/practice');const headers={Origin:new URL(page.url()).origin};
 const exported=await page.request.post('/api/generation',{headers,data:{action:'export',purpose:'passage',topic:'Synthetic capacity reading'}});expect(exported.ok()).toBe(true);
 const r=await exported.json(),itemId=r.scope.targets[0].id;
 const draft={version:1,kind:'passage',title:'Synthetic large review',japanese:'食べる、'.repeat(239)+'食べる。',translation:'Synthetic repeated eating.',uses:Array.from({length:240},(_,i)=>({itemId,start:i*4,end:i*4+3,reading:'ねる',sense:'synthetic deliberately flagged reading'})),support:[],issues:[],omissions:[],questions:[0,1].map(i=>({prompt:`Capacity question ${i}`,targetIds:[itemId],options:[{label:'A',text:'Eating'},{label:'B',text:'Sleeping'}],answer:'A',explanation:'Synthetic passage evidence.',evidence:{start:0,end:3}}))};
 const imported=await page.request.post('/api/generation',{headers,data:{action:'import',runId:r.id,draft,modelId:'synthetic'}});expect(imported.ok()).toBe(true);const v=await imported.json();expect(v.report.problems.length).toBe(240);
 const data={action:'approve',runId:r.id,approval:{confirmation:v.hash,reviewer:'Synthetic capacity reviewer',languageReviewed:true,acceptUntracked:true,answersReviewed:true,dispositions:v.report.problems.map((p:{key:string})=>({key:p.key,resolution:'checked_explanation',reason:'Synthetic review evidence. '.repeat(30)}))}};
 expect(JSON.stringify(data).length).toBeGreaterThan(64000);
 const incomplete=await page.request.post('/api/generation',{headers,data:{...data,approval:{...data.approval,dispositions:data.approval.dispositions.slice(1)}}});expect(incomplete.ok()).toBe(false);
 const approved=await page.request.post('/api/generation',{headers,data});expect(approved.ok()).toBe(true);expect((await approved.json()).status).toBe('approved');
});
