import { test, expect } from '@playwright/test';

// The review browser runner uses an isolated, synthetic database. Never write learner events in the real library.
test('recall → reveal → rate; committed response survives stop, reload and resume', async({page,request})=>{
 test.skip(!process.env.REVIEW_BROWSER_TEST, 'Requires isolated review browser runner');
 const denied=await request.post('/api/review',{headers:{Origin:'https://example.org'},data:{action:'start',includeNew:true}});
 expect(denied.status()).toBe(403);
 await page.goto('/review');
 await page.route('https://**/*',route=>route.abort());
 await page.getByRole('button',{name:'Continue learning',exact:true}).click();
 await page.getByRole('button',{name:'Study this new card'}).click();
 await expect(page.getByRole('heading',{name:'Study first'})).toBeVisible();
 await page.getByRole('button',{name:'Hide and recall'}).click();
 await expect(page.getByTestId('revealed-answer')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Dictionary',exact:true})).toBeDisabled();
 await page.getByLabel('Reading response').fill('しけん');
 await page.getByLabel('Meaning response').fill('a valid paraphrase');
 await page.getByRole('button',{name:'Commit response and reveal'}).click();
 await expect(page.getByTestId('revealed-answer')).toBeVisible();
 await page.waitForLoadState('networkidle');await page.screenshot({path:'.local/review-desktop.png',fullPage:true});
 await page.reload();
 await expect(page.getByTestId('revealed-answer')).toBeVisible();
 await page.getByRole('button',{name:'Stop and save'}).click();
 await page.reload();
 await page.getByRole('button',{name:'Resume reviews'}).click();
 await expect(page.getByTestId('revealed-answer')).toBeVisible();
 await expect(page.locator(".committed-answer")).toContainText("a valid paraphrase");
 await page.getByLabel('Reading recalled correctly').check();
 await page.getByLabel('Meaning recalled correctly').check();
 await page.getByRole('button',{name:'Good',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Saved');
 // Refresh an active revealed card and rate without a resume action.
 await page.getByRole('button',{name:'Study this new card'}).click();
 await page.getByRole('button',{name:'Hide and recall'}).click();
 await page.setViewportSize({width:375,height:812});
 await page.waitForLoadState('networkidle');await page.screenshot({path:'.local/review-mobile.png',fullPage:true});
 await page.getByLabel('Reading response').fill('しけん');
 await page.getByLabel('Meaning response').fill('forgot');
 await page.getByRole('button',{name:'Commit response and reveal'}).click();
 await page.reload();
 await page.getByLabel('Reading recalled correctly').check();
 await expect(page.getByRole('button',{name:'Good',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Again',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Saved · Again');
 await page.setViewportSize({width:375,height:812});
 expect(await page.locator('body').evaluate(el=>el.scrollWidth<=window.innerWidth)).toBe(true);
});

test('daily dashboard, stored grammar comparisons and explicit selected-text lookup',async({page})=>{
 test.skip(!process.env.REVIEW_BROWSER_TEST,'Requires synthetic database');
 await page.route('https://**/*',route=>route.abort());
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Your imported core pool'})).toBeVisible();
 await page.getByLabel('Default study block budget').fill('25');await page.getByRole('button',{name:'Save budget'}).click();
 await expect(page.getByText('Block budget saved. Daily card ceilings stay the same.')).toBeVisible();
 await page.reload();await expect(page.getByLabel('Default study block budget')).toHaveValue('25');
 await expect(page.getByRole('heading',{name:/Your saved block is ready|Ready for today/})).toBeVisible();await page.waitForLoadState('networkidle');await page.screenshot({path:'.local/phase3-dashboard-desktop.png',fullPage:true});
 await page.setViewportSize({width:375,height:812});await page.screenshot({path:'.local/phase3-dashboard-mobile.png',fullPage:true});
 const clear=await page.evaluate(()=>{const main=document.querySelector('main')!.getBoundingClientRect(),button=document.querySelector('.dictionary-trigger')!.getBoundingClientRect();return main.bottom<=button.top;});expect(clear).toBe(true);
 expect(await page.locator('body').evaluate(el=>el.scrollWidth<=window.innerWidth)).toBe(true);
 await page.goto('/grammar');await page.locator('[data-item-link]').first().click();
 await expect(page.getByRole('heading',{name:'Compare with…'})).toBeVisible();
 await expect(page.getByText('synthetic checked distinction')).toBeVisible();
 const links=page.locator('.comparison h3 a');const second=await links.nth(1).getAttribute('href');
 await page.goto(second!);await expect(page.getByText('synthetic checked distinction')).toBeVisible();
 await page.evaluate(()=>{const node=document.querySelector('h1')!;const range=document.createRange();range.selectNodeContents(node);const selection=window.getSelection()!;selection.removeAllRanges();selection.addRange(range);});
 await page.context().route('https://takoboto.jp/**',route=>route.fulfill({status:200,body:'Synthetic dictionary destination'}));
 const popupPromise=page.waitForEvent('popup');
 await page.getByRole('button',{name:'Dictionary',exact:true}).click();
 const popup=await popupPromise;await popup.waitForLoadState();
 expect(popup.url()).toBe('https://takoboto.jp/?q=%E3%80%9C%E3%82%82%E3%81%AE');
 expect(await popup.evaluate(()=>window.opener===null)).toBe(true);
 await popup.close();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.getByRole('button',{name:'Mark this item unfamiliar'}).click();await expect(page.getByText('Flagged for attention. Scheduling is unchanged.')).toBeVisible();
 await page.evaluate(()=>{window.getSelection()?.removeAllRanges();Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>{throw new DOMException('Denied','NotAllowedError');}}});});
 await page.getByRole('button',{name:'Dictionary',exact:true}).click();
 await expect(page.getByLabel('Word or phrase')).toBeFocused();
 await page.getByLabel('Word or phrase').fill('辞書 & 試験');
 const fallbackPopup=page.waitForEvent('popup');await page.getByRole('button',{name:'Open Takoboto'}).click();
 const destination=await fallbackPopup;await destination.waitForLoadState();
 expect(destination.url()).toBe('https://takoboto.jp/?q=%E8%BE%9E%E6%9B%B8%20%26%20%E8%A9%A6%E9%A8%93');await destination.close();
 await page.setViewportSize({width:1280,height:800});
 await page.getByRole('button',{name:'Dictionary',exact:true}).click();
 await expect(page.getByLabel('Word or phrase')).toBeVisible();
 await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Dictionary',exact:true})).toBeFocused();
});
