'use client';
import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import type { AssessmentView,AssessmentQuestion,AssessmentResult } from '@/lib/server/assessment/service.mjs';
type Send=(data:Record<string,unknown>)=>Promise<'saved'|'rejected'|'uncertain'>;
function Question({q,sessionId,send,busy}:{q:AssessmentQuestion;sessionId:string;send:Send;busy:boolean}){
 const [response,setResponse]=useState(q.answer?.response||''),[reading,setReading]=useState(q.answer?.reading||'');
 const [committing,setCommitting]=useState(false);const pending=useRef<Record<string,unknown>|null>(null);
 return <section className="assessment-question content-block"><p className="status">{q.domain} · {q.stratum}{q.baselineCheck?' · baseline check':''}{q.recentExposure?' · reviewed today':''}</p><h2 className="japanese" lang="ja">{q.prompt}</h2>
 <form onSubmit={async e=>{e.preventDefault();if(!pending.current)pending.current={action:'answer',sessionId,questionId:q.id,clientEventId:crypto.randomUUID(),answer:{response,...(q.objective==='vocab_reading_meaning'?{reading}:{})}};setCommitting(true);if(await send(pending.current)==='rejected'){pending.current=null;setCommitting(false);}}}>
 {q.objective==='vocab_reading_meaning'&&<label>Reading<input value={reading} onChange={e=>setReading(e.target.value)} maxLength={500} required disabled={!!q.answer||busy||committing} lang="ja"/></label>}
 {q.format==='multiple_choice'?<fieldset disabled={!!q.answer||busy||committing}><legend>Your answer</legend>{q.options.map(o=><label className="assessment-option" key={o.label}><input type="radio" name={q.id} value={o.label} checked={response===o.label} onChange={()=>setResponse(o.label)} required/><span lang="ja">{o.text}</span></label>)}</fieldset>:<label>Meaning / response<input value={response} onChange={e=>setResponse(e.target.value)} maxLength={2000} required disabled={!!q.answer||busy||committing}/></label>}
 {q.answer?<p className="status">Answer saved</p>:<button disabled={busy||!response.trim()||q.objective==='vocab_reading_meaning'&&!reading.trim()}>{committing?'Retry committed answer':'Commit answer'}</button>}
 </form></section>;
}
function Result({result:r,sessionId,send,busy}:{result:AssessmentResult;sessionId:string;send:Send;busy:boolean}){
 const [readingCorrect,setReading]=useState(false),[meaningCorrect,setMeaning]=useState(false);
 const grade=(outcome:string,components?:Record<string,boolean>)=>send({action:'grade',sessionId,questionId:r.questionId,outcome,...(components?{components}:{})});
 return <section className="assessment-result content-block"><p className="status">{r.domain} · {r.outcome}{r.assisted?' · assisted practice':''}{r.expired?' · timed segment expired':''} · {r.origin} origin</p><h2 lang="ja" className="japanese">{r.prompt}</h2><p>Your answer: {r.answer.reading?`${r.answer.reading} / `:''}{r.answer.response||'No timed answer'}</p><p>{r.rubric.expectedAnswer}</p><p>{r.rubric.explanation}</p>{r.sourceIds.map(id=><p key={id}><Link href={`/sources/${id}`}>Source evidence</Link></p>)}
 {r.canSelfGrade&&<div className="self-assessment">{r.objective==='vocab_reading_meaning'?<><label><input type="checkbox" checked={readingCorrect} onChange={e=>setReading(e.target.checked)} disabled={busy}/>Reading correct</label><label><input type="checkbox" checked={meaningCorrect} onChange={e=>setMeaning(e.target.checked)} disabled={busy}/>Meaning correct</label><button disabled={busy} onClick={()=>grade('correct',{readingCorrect,meaningCorrect})}>Save component score</button></>:<div className="review-actions"><button disabled={busy} onClick={()=>grade('correct')}>Correct</button><button disabled={busy} onClick={()=>grade('incorrect')}>Incorrect</button></div>}<p className="muted">Compare meaning with the checked rubric; equivalent paraphrases count.</p></div>}{r.canReport&&<button className="secondary" disabled={busy} onClick={()=>send({action:'report',sessionId,questionId:r.questionId})}>Question unclear — send for repair</button>}{r.repairRequested&&<p className="notice">Question reported; excluded from scoring and future samples until a reviewed correction.</p>}</section>;
}
export function Assessment({initial,availability}:{initial:AssessmentView|null;availability:{count:number;domains:Record<string,number>}|null}){
 const [view,setView]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[domain,setDomain]=useState('mixed'),[minutes,setMinutes]=useState(5),[remaining,setRemaining]=useState(0);
 const deadline=view?.timing?.deadline,serverRemaining=view?.timing?.remainingMs,completed=view?.status==='completed';
 useEffect(()=>{if(!deadline||completed)return;const received=performance.now();const tick=()=>setRemaining(Math.max(0,(serverRemaining||0)-(performance.now()-received)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[deadline,serverRemaining,completed]);
 const send:Send=async data=>{setBusy(true);setError('');try{const res=await fetch('/api/assessment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await res.json();if(!res.ok){setError(value.error||'Could not save');return [400,413].includes(res.status)?'rejected':'uncertain';}setView(value);history.replaceState(null,'',`/weekly?session=${value.sessionId}`);return 'saved';}catch(e){setError(e instanceof Error?e.message:'Could not save. Retry your answer.');return 'uncertain';}finally{setBusy(false);}};
 const done=view?.status==='completed',expired=!!view?.timing&&(view.timing.expired||!done&&remaining===0);
 return <div className="assessment"><p className="notice">Answers stay hidden until submission. Tests do not change review schedules. Short valid tests take priority over filling quotas.</p>{error&&<p role="alert" className="notice">{error}</p>}
 {!view?<form className="assessment-start" onSubmit={e=>{e.preventDefault();void send({action:'start',domain,size:20,readingMinutes:minutes});}}><label>Test scope<select value={domain} onChange={e=>setDomain(e.target.value)}><option value="mixed">Weekly mixed sample</option><option value="vocabulary">Vocabulary</option><option value="kanji">Kanji</option><option value="grammar">Grammar</option></select></label><label>Reading minutes<input type="number" min={1} max={15} value={minutes} onChange={e=>setMinutes(Number(e.target.value))} required/></label><p className="muted">The pilot reading budget is adjustable and is not official JLPT timing. It is fixed when the test starts.</p>{availability?.domains[domain]===0&&<p className="notice">No approved questions with eligible targets are available in this scope. Question answers, target links and supporting language need explicit review before a scored test.</p>}<button disabled={busy||availability?.domains[domain]===0}>Start cumulative test</button></form>:<>
 {done?<><h2>Your cumulative sample</h2><p>{view.summary?.correct} / {view.summary?.graded} correct in graded, unaided answers</p><p className="muted">{view.summary?.ungraded} ungraded · {view.summary?.assisted} assisted · {view.summary?.expired} expired. This sample does not predict a JLPT score.</p></>:<p>{view.questions.filter(q=>q.answer).length} answers saved · {view.total} questions selected{view.mode==='practice'?' · untimed assisted practice':''}</p>}
 <p className="status">{Object.entries(view.coverage).map(([d,n])=>`${d}: ${n}`).join(' · ')}</p>{view.omissions.map(o=><p className="muted" key={o}>{o}</p>)}
 {view.reading&&<section className="timed-reading"><p className="eyebrow">{view.mode==='practice'?'Assisted practice':'Timed reading'} · Furigana off · {view.reading.origin} origin</p><h2>{view.reading.title}</h2>{view.timing&&<><p data-testid="reading-deadline">Deadline: {view.timing.deadline}</p><p role="timer">{expired?'Timed result expired':done?'Submitted within reading budget':`${Math.ceil(remaining/1000)} seconds remaining`}</p></>}<p lang="ja" className="japanese reading-passage">{view.reading.japanese}</p>{!done&&<p className="muted">Definitions, translation, grammar help and dictionary lookup are disabled during scored reading. Background time counts.</p>}</section>}
 {!done&&view.questions.map(q=><Question key={`${view.sessionId}:${q.id}`} q={q} sessionId={view.sessionId} send={send} busy={busy||q.domain==='reading'&&expired}/>)}
 {!done&&view.readyForReading&&<button disabled={busy} onClick={()=>send({action:'reading',sessionId:view.sessionId})}>Present passage and start timer</button>}
 {!done&&!view.readyForReading&&<div className="review-actions"><button disabled={busy||view.questions.some(q=>!q.answer&&!(q.domain==='reading'&&expired))||view.total>view.questions.length} onClick={()=>send({action:'submit',sessionId:view.sessionId})}>Submit {view.mode==='practice'?'practice':'test'}</button><Link href="/">Leave and resume later</Link></div>}
 {done&&view.results?.map(r=><Result key={r.questionId} result={r} sessionId={view.sessionId} send={send} busy={busy}/>)}
 {done&&!!view.repairTargets?.length&&<div><h2>Choose up to three repairs</h2><p>Only failed primary targets are flagged. Review their reference, then use the existing daily learning flow for any explicit activation within its limits.</p>{view.repairTargets.map(id=><p key={id}><Link href={`/${view.results?.find(r=>r.primaryTargetItemId===id)?.targetKind}/${id}`}>Review flagged target</Link></p>)}</div>}
 {done&&view.reading&&view.mode!=='practice'&&<button className="secondary" disabled={busy} onClick={()=>send({action:'practice',sessionId:view.sessionId})}>Continue reading as separate practice</button>}
 {done&&<p><button className="secondary" disabled={busy} onClick={()=>{setView(null);history.replaceState(null,'','/weekly');}}>Prepare another sample</button></p>}
 </>}
 <p><a href="https://japanesetest4you.com/category/jlpt-n2/jlpt-n2-listening-test/" target="_blank" rel="noopener noreferrer">External N2 listening practice</a> · navigation does not record completion.</p><p><Link href="/">Back to daily study</Link></p></div>;
}
