'use client';
import { useState } from 'react';
import type { Run,RunSummary } from '@/lib/server/generation/service.mjs';
import type { ProviderConfiguration } from '@/lib/server/generation/gemini.mjs';
import { PracticeReading } from './practice-reading';
const failureMessage=(run:Run)=>run.report?.failure==='network'?'Generation timed out or could not connect. Please try again later.':run.report?.failure==='quota'?'Generation limit reached. Read saved practice and try again later.':'The passage could not be validated. Please try again later.';
export function Practice({poolCount,initialRuns,provider}:{poolCount:number;initialRuns:RunSummary[];provider:ProviderConfiguration}){
 const [run,setRun]=useState<Run|null>(null),[runs,setRuns]=useState(initialRuns),[busy,setBusy]=useState(false),[error,setError]=useState(''),[topic,setTopic]=useState('Everyday life'),[reviewer,setReviewer]=useState(''),[checked,setChecked]=useState(false),[accept,setAccept]=useState(false),[answers,setAnswers]=useState(false),[reasons,setReasons]=useState<Record<string,string>>({}),[problem,setProblem]=useState(''),[modelReview,setModelReview]=useState(true);
 function resetApproval(){setChecked(false);setAccept(false);setAnswers(false);setReasons({});}
 async function refresh(){const r=await fetch('/api/generation',{cache:'no-store'});if(r.ok)setRuns((await r.json()).runs);}
 async function mutate(data:unknown){setBusy(true);setError('');try{const response=await fetch('/api/generation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw new Error(value.error);if(value.hidden)setRun(null);else if(value.status==='failed')setError(failureMessage(value));else setRun(value);}catch(e){setError(e instanceof Error?e.message:'Practice unavailable');}finally{await refresh().catch(()=>{});setBusy(false);}}
 async function open(id:string){setBusy(true);setError('');try{const r=await fetch(`/api/generation?run=${encodeURIComponent(id)}`,{cache:'no-store'}),value=await r.json();if(!r.ok)throw new Error(value.error);if(value.status==='failed'){setError(failureMessage(value));return;}setRun(value);resetApproval();}catch(e){setError(e instanceof Error?e.message:'Could not resume practice');}finally{setBusy(false);}}
 const problems=run?.report?.problems||[],omissions=run?.draft?.omissions||[];
 const ready=checked&&(!run?.report?.untracked.length||accept)&&(!run?.draft?.questions.length||answers)&&problems.every(p=>reasons[p.key]?.trim())&&run?.report?.analyzerStatus==='ready';
 return <section className="practice" aria-label="Contextual practice" aria-busy={busy}>
  {error&&<div role="alert" className="practice-alert"><p>{error}</p><button type="button" className="secondary" onClick={()=>setError('')}>Dismiss</button></div>}
  <form className="practice-compose" onSubmit={e=>{e.preventDefault();resetApproval();void mutate({action:'generate',purpose:'passage',topic,review:modelReview});}}>
   <h2>A passage from your studies</h2><p className="muted">Up to 15 sentence lines, blending your latest study week with earlier material.</p>
   {!poolCount&&<p className="notice">Mark an approved item as studied to begin.</p>}
   <label htmlFor="practice-topic">What would you like to read about?</label><input id="practice-topic" value={topic} maxLength={200} required onChange={e=>setTopic(e.target.value)}/>
   <div className="practice-compose-actions"><label className="practice-check"><input type="checkbox" checked={modelReview} onChange={e=>setModelReview(e.target.checked)}/>Include an AI language review</label><button disabled={busy||!poolCount||!provider.enabled}>{busy?'Generating…':'Generate'}</button></div>
   <p className="status" role="status">{busy?'Writing and checking your passage. This may take a moment.':provider.enabled?'Saved as a draft for ungraded reading. Up to 10 requests per rolling 24 hours.':'Generation unavailable. '+provider.reason}</p>
  </form>
  {run?.draft&&<article className="content-block practice-output">
   <div className="practice-heading"><h2>{run.draft.title}</h2><span className="badge generated">Generated · {run.status==='approved'?'human reviewed':run.status==='retired'?'retired':'unverified draft'}</span></div>
   <PracticeReading key={`${run.id}-${run.revision}`} run={run}/>
   <details className="practice-coverage"><summary>Study coverage · {new Set(run.draft.uses.map(u=>u.itemId)).size} of {run.scope.targets.length} items</summary><p className="status">Recently studied and older items included in this passage.</p><div className="coverage-words">{run.scope.targets.filter(t=>run.draft!.uses.some(u=>u.itemId===t.id)).map(t=><span key={t.id} lang="ja">{t.writtenForm}</span>)}</div>{omissions.length>0&&<><h3>Not included in this passage</h3>{omissions.map(o=><p key={o.itemId}><span lang="ja">{run.scope.targets.find(t=>t.id===o.itemId)?.writtenForm}</span> — {o.reason}</p>)}</>}</details>
   {run.draft.questions.length>0&&<section className="practice-questions" aria-label="Comprehension practice"><h3>Check your understanding</h3>{run.draft.questions.map((q,i)=><div className="practice-question" key={i}><p lang="ja">{q.prompt}</p><ol>{q.options.map(o=><li key={o.label} lang="ja">{o.label}: {o.text}</li>)}</ol><details><summary>Show proposed answer · ungraded</summary><p>{q.answer} · {q.explanation}</p><p lang="ja">{run.draft!.japanese.slice(q.evidence.start,q.evidence.end)}</p></details></div>)}</section>}
   {run.report?.providerReport&&<details className="practice-ai-review"><summary>AI language review</summary><p>{run.report.providerReport.modelReview?.summary||'AI review unavailable. This remains an unverified draft.'}</p>{run.report.providerReport.modelReview?.findings.map((f,i)=><p key={i}>{f.reason}</p>)}</details>}
   {run.status==='draft'&&<details className="publication-review"><summary><span>Review before publication<small>Optional · approve this passage for reuse</small></span></summary><form onSubmit={e=>{e.preventDefault();void mutate({action:'approve',runId:run.id,approval:{confirmation:run.hash,reviewer,languageReviewed:checked,acceptUntracked:accept,answersReviewed:answers,dispositions:problems.map(p=>({key:p.key,resolution:'checked_explanation',reason:reasons[p.key]||''}))}});}}>
    <p>Check the Japanese and proposed answers before adding this passage to reusable practice.</p><label>Reviewer<input value={reviewer} required maxLength={100} autoComplete="name" onChange={e=>setReviewer(e.target.value)}/></label>
    {problems.length>0&&<section className="publication-findings"><h3>{problems.length} {problems.length===1?'point':'points'} to check</h3>{problems.map(p=><label key={p.key}><span>{p.reason}</span><textarea aria-label={`Checked resolution for ${p.code}`} required placeholder="How did you resolve this?" value={reasons[p.key]||''} onChange={e=>setReasons({...reasons,[p.key]:e.target.value})}/></label>)}</section>}
    <fieldset><legend>Review checklist</legend><label className="practice-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I checked Japanese, contextual readings, senses and translation.</label><label className="practice-check"><input type="checkbox" checked={accept} onChange={e=>setAccept(e.target.checked)}/>I accept untracked support for this content without marking it familiar.</label>{run.draft.questions.length>0&&<label className="practice-check"><input type="checkbox" checked={answers} onChange={e=>setAnswers(e.target.checked)}/>I checked both answers, distractors and passage evidence.</label>}</fieldset>
    {run.report?.analyzerStatus!=='ready'&&<p className="notice">Japanese analysis is unavailable. Approval is paused.</p>}<button disabled={busy||!ready}>Approve for reuse</button>
   </form></details>}
   {run.status==='approved'&&<details><summary>Report a problem</summary><form onSubmit={e=>{e.preventDefault();void mutate({action:'report',runId:run.id,reason:problem});}}><label>Report a problem<input value={problem} maxLength={1000} required onChange={e=>setProblem(e.target.value)}/></label><button disabled={busy}>Report and retire</button></form></details>}
   <div className="practice-output-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>void mutate({action:'hide',runId:run.id})}>Hide this item</button></div>
  </article>}
  <section className="saved-practice" aria-label="Saved practice"><h2>Saved practice</h2>{runs.length?<ul className="practice-history">{runs.map(r=><li key={r.id}><button className="secondary" type="button" disabled={busy} onClick={()=>void open(r.id)}><span>{r.topic}</span><small>{r.status==='approved'?'Reviewed':r.status==='retired'?'Retired':'Draft'}</small></button></li>)}</ul>:<p className="muted">Your passages will appear here after a successful generation.</p>}</section>
 </section>;
}
