import Link from 'next/link';
import type { GrammarComparison, StudyContent, StudySource } from '@/lib/server/content/study.mjs';
export function StudySources({sources}:{sources:StudySource[]}){if(!sources.length)return null;return <details><summary>Sources &amp; evidence</summary><p className="status">{sources.map((s,i)=><span key={s.id}>{i>0?' · ':''}<Link href={`/sources/${s.sourceId}?record=${s.id}#record-${s.id}`}>{s.source.title}{s.printedPage?` · p. ${s.printedPage}`:''}</Link></span>)}</p></details>;}
export function Comparisons({comparisons}:{comparisons:GrammarComparison[]}){if(!comparisons.length)return null;return <section aria-label="Grammar comparisons"><h2>Compare with…</h2>{comparisons.map(c=><article key={c.id} className="comparison"><p className="field-label">{c.origin==='book'?'Book':c.origin==='generated'?'Generated · approved':'User · approved'} comparison</p><p>{c.difference}</p><div className="comparison-patterns">{c.patterns.map(p=><div key={p.itemId}><h3><Link href={`/grammar/${p.itemId}`} lang="ja">{p.pattern}</Link></h3><p className="japanese sentence" lang="ja">{p.example.japanese}</p>{p.example.translation&&<p>{p.example.translation}</p>}<p className="field-label">{p.example.origin} example</p><StudySources sources={p.example.sources}/></div>)}</div><StudySources sources={c.sources}/></article>)}</section>;}
export function StudyBack({study}:{study:StudyContent|null|undefined}){if(!study)return null;return <section className="study-back" aria-label="Stored study reference">
 {study.readings&&<div><h3>Source readings</h3><p lang="ja">On: {study.readings.on.join(' · ')||'Not supplied'} · Kun: {study.readings.kun.join(' · ')||'Not supplied'}</p><StudySources sources={study.sources}/></div>}
 {study.grammar&&<><h3>Formation</h3>{study.grammar.formation.length?study.grammar.formation.map((f,i)=><p lang="ja" key={i}>{f}</p>):<p className="muted">Formation not supplied.</p>}<h3>{study.grammar.guidanceLabel}</h3><p>{study.grammar.guidance||'Approved explanation unavailable.'}</p><p className="field-label">{study.grammar.guidanceOrigin} guidance</p><StudySources sources={study.grammar.sources}/><Comparisons comparisons={study.grammar.comparisons}/></>}
 <h3>Examples &amp; source words</h3>{study.examples.length?study.examples.map(e=><article key={e.id} className="study-example"><p className="field-label">{e.origin==='book'?'Book original':`${e.origin} · approved supplement`}</p><p className="japanese sentence" lang="ja">{e.japanese}</p>{e.reading&&<p lang="ja" className="reading">{e.reading}</p>}{e.translation&&<p>{e.translation}</p>}<StudySources sources={e.sources}/></article>):<p className="muted">No approved examples supplied.</p>}
 </section>;}
